a,b,c,d,e = map(int,input().split())
ans = []
ans.append(("A",a))
ans.append(("B",b))
ans.append(("C",c))
ans.append(("D",d))
ans.append(("E",e))
ans.append(("AB",a+b))
ans.append(("AC",a+c))
ans.append(("AD",a+d))
ans.append(("AE",a+e))
ans.append(("BC",b+c))
ans.append(("BD",b+d))
ans.append(("BE",b+e))
ans.append(("CD",c+d))
ans.append(("CE",c+e))
ans.append(("DE",d+e))
ans.append(("ABC",a+b+c))
ans.append(("ABD",a+b+d))
ans.append(("ABE",a+b+e))
ans.append(("ACD",a+c+d))
ans.append(("ACE",a+c+e))
ans.append(("ADE",a+d+e))
ans.append(("BCD",b+c+d))
ans.append(("BCE",b+c+e))
ans.append(("BDE",b+d+e))
ans.append(("CDE",c+d+e))
ans.append(("BCDE",b+c+d+e))
ans.append(("ACDE",a+c+d+e))
ans.append(("ABDE",a+b+d+e))
ans.append(("ABCE",a+b+c+e))
ans.append(("ABCD",a+b+c+d))
ans.append(("ABCDE",a+b+c+d+e))
ans.sort(key=lambda x: (-x[1],x[0]))
for i in range(31):
    print(ans[i][0])